// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/libpcap_remote.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_485463ef1761b568, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type ListInterfacesReply struct {
	InterfaceList        map[string]*ListInterfacesReply_Interface `protobuf:"bytes,1,rep,name=interfaceList,proto3" json:"interfaceList,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *ListInterfacesReply) Reset()         { *m = ListInterfacesReply{} }
func (m *ListInterfacesReply) String() string { return proto.CompactTextString(m) }
func (*ListInterfacesReply) ProtoMessage()    {}
func (*ListInterfacesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_485463ef1761b568, []int{1}
}

func (m *ListInterfacesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListInterfacesReply.Unmarshal(m, b)
}
func (m *ListInterfacesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListInterfacesReply.Marshal(b, m, deterministic)
}
func (m *ListInterfacesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListInterfacesReply.Merge(m, src)
}
func (m *ListInterfacesReply) XXX_Size() int {
	return xxx_messageInfo_ListInterfacesReply.Size(m)
}
func (m *ListInterfacesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListInterfacesReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListInterfacesReply proto.InternalMessageInfo

func (m *ListInterfacesReply) GetInterfaceList() map[string]*ListInterfacesReply_Interface {
	if m != nil {
		return m.InterfaceList
	}
	return nil
}

type ListInterfacesReply_Interface struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListInterfacesReply_Interface) Reset()         { *m = ListInterfacesReply_Interface{} }
func (m *ListInterfacesReply_Interface) String() string { return proto.CompactTextString(m) }
func (*ListInterfacesReply_Interface) ProtoMessage()    {}
func (*ListInterfacesReply_Interface) Descriptor() ([]byte, []int) {
	return fileDescriptor_485463ef1761b568, []int{1, 1}
}

func (m *ListInterfacesReply_Interface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListInterfacesReply_Interface.Unmarshal(m, b)
}
func (m *ListInterfacesReply_Interface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListInterfacesReply_Interface.Marshal(b, m, deterministic)
}
func (m *ListInterfacesReply_Interface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListInterfacesReply_Interface.Merge(m, src)
}
func (m *ListInterfacesReply_Interface) XXX_Size() int {
	return xxx_messageInfo_ListInterfacesReply_Interface.Size(m)
}
func (m *ListInterfacesReply_Interface) XXX_DiscardUnknown() {
	xxx_messageInfo_ListInterfacesReply_Interface.DiscardUnknown(m)
}

var xxx_messageInfo_ListInterfacesReply_Interface proto.InternalMessageInfo

func (m *ListInterfacesReply_Interface) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListInterfacesReply_Interface) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "pcap_remote.Empty")
	proto.RegisterType((*ListInterfacesReply)(nil), "pcap_remote.ListInterfacesReply")
	proto.RegisterMapType((map[string]*ListInterfacesReply_Interface)(nil), "pcap_remote.ListInterfacesReply.InterfaceListEntry")
	proto.RegisterType((*ListInterfacesReply_Interface)(nil), "pcap_remote.ListInterfacesReply.Interface")
}

func init() { proto.RegisterFile("pb/libpcap_remote.proto", fileDescriptor_485463ef1761b568) }

var fileDescriptor_485463ef1761b568 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x4d, 0x6b, 0x95, 0x4c, 0x50, 0x74, 0x3c, 0x18, 0x72, 0x0a, 0x39, 0x45, 0x85, 0x04,
	0x92, 0x8b, 0x78, 0x52, 0xa1, 0x60, 0x41, 0xb0, 0x6c, 0x4f, 0x0a, 0x22, 0xc9, 0x3a, 0xd6, 0xc5,
	0xfc, 0x59, 0x36, 0xdb, 0x40, 0x3e, 0x8e, 0xdf, 0x54, 0xba, 0xfe, 0x21, 0x51, 0x41, 0x6f, 0xc3,
	0xdb, 0x7d, 0xf3, 0x7b, 0xcc, 0x83, 0x43, 0x99, 0xc7, 0x85, 0xc8, 0x25, 0xcf, 0xe4, 0x83, 0xa2,
	0xb2, 0xd6, 0x14, 0x49, 0x55, 0xeb, 0x1a, 0x9d, 0x9e, 0x14, 0x6c, 0xc3, 0x64, 0x5a, 0x4a, 0xdd,
	0x05, 0xaf, 0x23, 0x38, 0xb8, 0x16, 0x8d, 0x9e, 0x55, 0x9a, 0xd4, 0x53, 0xc6, 0xa9, 0x61, 0x24,
	0x8b, 0x0e, 0x6f, 0x61, 0x47, 0x7c, 0x4a, 0xeb, 0x77, 0xd7, 0xf2, 0xc7, 0xa1, 0x93, 0xa4, 0x51,
	0x7f, 0xf1, 0x2f, 0xc6, 0x68, 0xd6, 0x77, 0x4d, 0x2b, 0xad, 0x3a, 0x36, 0xdc, 0xe4, 0x15, 0x80,
	0x3f, 0x3f, 0xe1, 0x1e, 0x8c, 0x5f, 0xa8, 0x73, 0x2d, 0xdf, 0x0a, 0x6d, 0xb6, 0x1e, 0xf1, 0x1c,
	0x26, 0x6d, 0x56, 0xac, 0xc8, 0x1d, 0xf9, 0x56, 0xe8, 0x24, 0xc7, 0xff, 0x47, 0xb3, 0x77, 0xe3,
	0xd9, 0xe8, 0xd4, 0xf2, 0x2e, 0xc0, 0xfe, 0xd2, 0x11, 0x61, 0xb3, 0xca, 0x4a, 0xfa, 0xa0, 0x98,
	0x19, 0x7d, 0x70, 0x1e, 0xa9, 0xe1, 0x4a, 0x48, 0x2d, 0xea, 0xca, 0xc0, 0x6c, 0xd6, 0x97, 0x92,
	0x7b, 0xd8, 0x9f, 0xf3, 0x4c, 0x32, 0x43, 0x5e, 0x90, 0x6a, 0x05, 0x27, 0xbc, 0x82, 0xdd, 0x61,
	0x06, 0xc4, 0x41, 0x40, 0x73, 0x5e, 0xcf, 0xff, 0x2b, 0x74, 0xb0, 0x71, 0x79, 0x72, 0x77, 0xb4,
	0x14, 0xfa, 0x79, 0x95, 0x47, 0xbc, 0x2e, 0xe3, 0xc5, 0x9c, 0xdd, 0x2c, 0x1b, 0x4d, 0xea, 0x5b,
	0x8b, 0x71, 0x9b, 0xc6, 0x32, 0xcf, 0xb7, 0x4c, 0x99, 0xe9, 0x5b, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x59, 0xbe, 0x32, 0x29, 0xe7, 0x01, 0x00, 0x00,
}
