// Code generated by protoc-gen-go. DO NOT EDIT.
// source: libpcap_remote.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_63ba5107323985b1, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type ListInterfacesReply struct {
	InterfaceList        map[string]*ListInterfacesReply_Interface `protobuf:"bytes,1,rep,name=interfaceList,proto3" json:"interfaceList,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *ListInterfacesReply) Reset()         { *m = ListInterfacesReply{} }
func (m *ListInterfacesReply) String() string { return proto.CompactTextString(m) }
func (*ListInterfacesReply) ProtoMessage()    {}
func (*ListInterfacesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_63ba5107323985b1, []int{1}
}

func (m *ListInterfacesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListInterfacesReply.Unmarshal(m, b)
}
func (m *ListInterfacesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListInterfacesReply.Marshal(b, m, deterministic)
}
func (m *ListInterfacesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListInterfacesReply.Merge(m, src)
}
func (m *ListInterfacesReply) XXX_Size() int {
	return xxx_messageInfo_ListInterfacesReply.Size(m)
}
func (m *ListInterfacesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListInterfacesReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListInterfacesReply proto.InternalMessageInfo

func (m *ListInterfacesReply) GetInterfaceList() map[string]*ListInterfacesReply_Interface {
	if m != nil {
		return m.InterfaceList
	}
	return nil
}

type ListInterfacesReply_Interface struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListInterfacesReply_Interface) Reset()         { *m = ListInterfacesReply_Interface{} }
func (m *ListInterfacesReply_Interface) String() string { return proto.CompactTextString(m) }
func (*ListInterfacesReply_Interface) ProtoMessage()    {}
func (*ListInterfacesReply_Interface) Descriptor() ([]byte, []int) {
	return fileDescriptor_63ba5107323985b1, []int{1, 1}
}

func (m *ListInterfacesReply_Interface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListInterfacesReply_Interface.Unmarshal(m, b)
}
func (m *ListInterfacesReply_Interface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListInterfacesReply_Interface.Marshal(b, m, deterministic)
}
func (m *ListInterfacesReply_Interface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListInterfacesReply_Interface.Merge(m, src)
}
func (m *ListInterfacesReply_Interface) XXX_Size() int {
	return xxx_messageInfo_ListInterfacesReply_Interface.Size(m)
}
func (m *ListInterfacesReply_Interface) XXX_DiscardUnknown() {
	xxx_messageInfo_ListInterfacesReply_Interface.DiscardUnknown(m)
}

var xxx_messageInfo_ListInterfacesReply_Interface proto.InternalMessageInfo

func (m *ListInterfacesReply_Interface) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListInterfacesReply_Interface) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type StartCaptureRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Device               string   `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	SnapshotLen          uint32   `protobuf:"varint,3,opt,name=snapshot_len,json=snapshotLen,proto3" json:"snapshot_len,omitempty"`
	Promiscuous          bool     `protobuf:"varint,4,opt,name=promiscuous,proto3" json:"promiscuous,omitempty"`
	PcapFilter           string   `protobuf:"bytes,5,opt,name=pcap_filter,json=pcapFilter,proto3" json:"pcap_filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartCaptureRequest) Reset()         { *m = StartCaptureRequest{} }
func (m *StartCaptureRequest) String() string { return proto.CompactTextString(m) }
func (*StartCaptureRequest) ProtoMessage()    {}
func (*StartCaptureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_63ba5107323985b1, []int{2}
}

func (m *StartCaptureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartCaptureRequest.Unmarshal(m, b)
}
func (m *StartCaptureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartCaptureRequest.Marshal(b, m, deterministic)
}
func (m *StartCaptureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartCaptureRequest.Merge(m, src)
}
func (m *StartCaptureRequest) XXX_Size() int {
	return xxx_messageInfo_StartCaptureRequest.Size(m)
}
func (m *StartCaptureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartCaptureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartCaptureRequest proto.InternalMessageInfo

func (m *StartCaptureRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *StartCaptureRequest) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *StartCaptureRequest) GetSnapshotLen() uint32 {
	if m != nil {
		return m.SnapshotLen
	}
	return 0
}

func (m *StartCaptureRequest) GetPromiscuous() bool {
	if m != nil {
		return m.Promiscuous
	}
	return false
}

func (m *StartCaptureRequest) GetPcapFilter() string {
	if m != nil {
		return m.PcapFilter
	}
	return ""
}

type StopCaptureRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopCaptureRequest) Reset()         { *m = StopCaptureRequest{} }
func (m *StopCaptureRequest) String() string { return proto.CompactTextString(m) }
func (*StopCaptureRequest) ProtoMessage()    {}
func (*StopCaptureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_63ba5107323985b1, []int{3}
}

func (m *StopCaptureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopCaptureRequest.Unmarshal(m, b)
}
func (m *StopCaptureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopCaptureRequest.Marshal(b, m, deterministic)
}
func (m *StopCaptureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopCaptureRequest.Merge(m, src)
}
func (m *StopCaptureRequest) XXX_Size() int {
	return xxx_messageInfo_StopCaptureRequest.Size(m)
}
func (m *StopCaptureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopCaptureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopCaptureRequest proto.InternalMessageInfo

func (m *StopCaptureRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type Packet struct {
	LinkType      int32 `protobuf:"varint,1,opt,name=linkType,proto3" json:"linkType,omitempty"`
	Ts            int64 `protobuf:"varint,2,opt,name=ts,proto3" json:"ts,omitempty"`
	CaptureLength int32 `protobuf:"varint,3,opt,name=captureLength,proto3" json:"captureLength,omitempty"`
	// Length is the size of the original packet.  Should always be >=
	// CaptureLength.
	Length int32 `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	// InterfaceIndex
	InterfaceIndex int32  `protobuf:"varint,5,opt,name=InterfaceIndex,proto3" json:"InterfaceIndex,omitempty"`
	Payload        []byte `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	// Aux data
	Vlan                 uint32   `protobuf:"varint,7,opt,name=vlan,proto3" json:"vlan,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_63ba5107323985b1, []int{4}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetLinkType() int32 {
	if m != nil {
		return m.LinkType
	}
	return 0
}

func (m *Packet) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *Packet) GetCaptureLength() int32 {
	if m != nil {
		return m.CaptureLength
	}
	return 0
}

func (m *Packet) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *Packet) GetInterfaceIndex() int32 {
	if m != nil {
		return m.InterfaceIndex
	}
	return 0
}

func (m *Packet) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Packet) GetVlan() uint32 {
	if m != nil {
		return m.Vlan
	}
	return 0
}

func init() {
	proto.RegisterType((*Empty)(nil), "pcap_remote.Empty")
	proto.RegisterType((*ListInterfacesReply)(nil), "pcap_remote.ListInterfacesReply")
	proto.RegisterMapType((map[string]*ListInterfacesReply_Interface)(nil), "pcap_remote.ListInterfacesReply.InterfaceListEntry")
	proto.RegisterType((*ListInterfacesReply_Interface)(nil), "pcap_remote.ListInterfacesReply.Interface")
	proto.RegisterType((*StartCaptureRequest)(nil), "pcap_remote.StartCaptureRequest")
	proto.RegisterType((*StopCaptureRequest)(nil), "pcap_remote.StopCaptureRequest")
	proto.RegisterType((*Packet)(nil), "pcap_remote.Packet")
}

func init() { proto.RegisterFile("libpcap_remote.proto", fileDescriptor_63ba5107323985b1) }

var fileDescriptor_63ba5107323985b1 = []byte{
	// 500 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xee, 0x3a, 0x71, 0xda, 0x8c, 0x93, 0xe8, 0xf7, 0x9b, 0x20, 0x64, 0xf9, 0x52, 0x63, 0x21,
	0x64, 0x71, 0x88, 0x50, 0x7a, 0x41, 0x9c, 0xf8, 0x57, 0x44, 0xa4, 0x1c, 0xaa, 0x0d, 0x17, 0xb8,
	0x54, 0x1b, 0x67, 0x4a, 0xad, 0x38, 0xeb, 0xc5, 0x5e, 0x47, 0xf8, 0x71, 0x38, 0xf1, 0x2a, 0x3c,
	0x0d, 0xcf, 0x80, 0xbc, 0x4e, 0x22, 0x3b, 0x44, 0x2a, 0xb7, 0x99, 0x6f, 0x76, 0xbe, 0xf9, 0xf7,
	0x2d, 0x3c, 0x4a, 0xe2, 0xa5, 0x8a, 0x84, 0xba, 0xcd, 0x68, 0x93, 0x6a, 0x9a, 0xa8, 0x2c, 0xd5,
	0x29, 0x3a, 0x0d, 0x28, 0x38, 0x07, 0xfb, 0x7a, 0xa3, 0x74, 0x19, 0xfc, 0xb0, 0x60, 0x3c, 0x8f,
	0x73, 0x3d, 0x93, 0x9a, 0xb2, 0x3b, 0x11, 0x51, 0xce, 0x49, 0x25, 0x25, 0x7e, 0x86, 0x61, 0xbc,
	0x87, 0xaa, 0xb8, 0xcb, 0xfc, 0x4e, 0xe8, 0x4c, 0xaf, 0x26, 0x4d, 0xe2, 0x13, 0x89, 0x93, 0x59,
	0x33, 0xeb, 0x5a, 0xea, 0xac, 0xe4, 0x6d, 0x26, 0x2f, 0x01, 0xfc, 0xfb, 0x11, 0xfe, 0x07, 0x9d,
	0x35, 0x95, 0x2e, 0xf3, 0x59, 0xd8, 0xe7, 0x95, 0x89, 0xaf, 0xc1, 0xde, 0x8a, 0xa4, 0x20, 0xd7,
	0xf2, 0x59, 0xe8, 0x4c, 0x9f, 0xff, 0x7b, 0x69, 0x5e, 0x27, 0xbe, 0xb2, 0x5e, 0x32, 0xef, 0x0d,
	0xf4, 0x0f, 0x38, 0x22, 0x74, 0xa5, 0xd8, 0xd0, 0xae, 0x8a, 0xb1, 0xd1, 0x07, 0x67, 0x45, 0x79,
	0x94, 0xc5, 0x4a, 0xc7, 0xa9, 0x34, 0xc5, 0xfa, 0xbc, 0x09, 0x05, 0x3f, 0x19, 0x8c, 0x17, 0x5a,
	0x64, 0xfa, 0x9d, 0x50, 0xba, 0xc8, 0x88, 0xd3, 0xb7, 0x82, 0x72, 0x5d, 0xb1, 0x15, 0x45, 0xbc,
	0xda, 0xb3, 0x55, 0x36, 0x3e, 0x86, 0xde, 0x8a, 0xb6, 0x71, 0x44, 0x3b, 0xa2, 0x9d, 0x87, 0x4f,
	0x60, 0x90, 0x4b, 0xa1, 0xf2, 0xfb, 0x54, 0xdf, 0x26, 0x24, 0xdd, 0x8e, 0xcf, 0xc2, 0x21, 0x77,
	0xf6, 0xd8, 0x9c, 0x64, 0xd5, 0x88, 0xca, 0xd2, 0x4d, 0x9c, 0x47, 0x45, 0x5a, 0xe4, 0x6e, 0xd7,
	0x67, 0xe1, 0x05, 0x6f, 0x42, 0x78, 0x09, 0xf5, 0x11, 0xef, 0xe2, 0x44, 0x53, 0xe6, 0xda, 0xa6,
	0x02, 0x54, 0xd0, 0x07, 0x83, 0x04, 0x21, 0xe0, 0x42, 0xa7, 0xea, 0xe1, 0x3e, 0x83, 0x5f, 0x0c,
	0x7a, 0x37, 0x22, 0x5a, 0x93, 0x46, 0x0f, 0x2e, 0x92, 0x58, 0xae, 0x3f, 0x95, 0xaa, 0x5e, 0x8c,
	0xcd, 0x0f, 0x3e, 0x8e, 0xc0, 0xd2, 0xb9, 0x19, 0xa5, 0xc3, 0x2d, 0x9d, 0xe3, 0x53, 0x18, 0x46,
	0x35, 0xf9, 0x9c, 0xe4, 0x57, 0x7d, 0x6f, 0xe6, 0xb0, 0x79, 0x1b, 0xac, 0x96, 0x90, 0xd4, 0xe1,
	0xae, 0x09, 0xef, 0x3c, 0x7c, 0x06, 0xa3, 0xc3, 0x2d, 0x66, 0x72, 0x45, 0xdf, 0xcd, 0x08, 0x36,
	0x3f, 0x42, 0xd1, 0x85, 0x73, 0x25, 0xca, 0x24, 0x15, 0x2b, 0xb7, 0xe7, 0xb3, 0x70, 0xc0, 0xf7,
	0x6e, 0x35, 0xca, 0x36, 0x11, 0xd2, 0x3d, 0x37, 0xeb, 0x33, 0xf6, 0xf4, 0x37, 0x83, 0xff, 0x6f,
	0x22, 0xa1, 0xb8, 0x51, 0xc6, 0x82, 0x32, 0xb3, 0xf0, 0x8f, 0x30, 0x6a, 0x6b, 0x04, 0xb1, 0x25,
	0x20, 0x23, 0x7f, 0xcf, 0x7f, 0x48, 0x54, 0xc1, 0x19, 0xce, 0x60, 0xd0, 0xbc, 0x3e, 0xb6, 0x73,
	0x4e, 0x08, 0xc3, 0x1b, 0xb7, 0x5e, 0xd4, 0x6b, 0x0e, 0xce, 0x5e, 0x30, 0x7c, 0x0f, 0x4e, 0xe3,
	0x3e, 0x78, 0x79, 0xc4, 0x74, 0x7c, 0x39, 0xef, 0x44, 0xcb, 0xc1, 0xd9, 0xdb, 0xee, 0x17, 0x4b,
	0x2d, 0x97, 0x3d, 0xf3, 0xad, 0xaf, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x89, 0x0a, 0x1e,
	0xee, 0x03, 0x00, 0x00,
}
